-- Edible and toxic plants for deco.lua

-- Globals
minimal = minimal
deco = deco or {}

-- Import
local path = minetest.get_modpath("mapgen")
local sna = dofile(path.."/soils_and_altitudes.lua")

local edible_plants = {
    {--[[wetland:Galanta]]
        name = "nodes_nature:galanta",
        deco_type = "simple",
        place_on = sna.wetland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0040, spread={x=32, y=32, z=32}, seed=153, octaves=2, persist=0.8},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:galanta",
        param2 = 4,
    },

    {--[[wetland:Malinka]]
        name = "nodes_nature:malinka",
        deco_type = "simple",
        place_on = sna.wetland_on,
        sidelen = 80,
        fill_ratio = 0.001200,
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:malinka",
        param2 = 1,
    },

    {--[[forest:Vansano]]
        name = "fr_nn:vansano",
        deco_type = "simple",
        place_on = sna.forest_on,
        sidelen = 80,
        fill_ratio = 0.010000,
        y_max = sna.lowland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:vansano",
        param2 = 2,
    },

    {--[[forest:Momo]]
        name = "fr_nn:momo_fruiting",
        deco_type = "simple",
        place_on = sna.forest_on,
        sidelen = 80,
        fill_ratio = 0.001200,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:momo_fruiting",
        param2 = 2,
    },

    {--[[forest:Rzepicha]]
        name = "fr_nn:rzepicha_fruiting",
        deco_type = "simple",
        place_on = sna.forest_on,
        sidelen = 80,
        fill_ratio = 0.000090,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:rzepicha_fruiting",
        param2 = 0,
    },

    {--[[forest:Malina]]
        name = "fr_nn:malina_fruiting",
        deco_type = "simple",
        place_on = sna.forest_on,
        sidelen = 80,
        fill_ratio = 0.000700,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:malina_fruiting",
        param2 = 3,
    },

    {--[[forest:Yellow Malina]]
        name = "fr_nn:yellow_malina_fruiting",
        deco_type = "simple",
        place_on = sna.forest_on,
        sidelen = 80,
        fill_ratio = 0.000100,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:yellow_malina_fruiting",
        param2 = 3,
    },

    {--[[forest:Zufani]]
        name = "fr_nn:zufani",
        deco_type = "simple",
        place_on = sna.forest_on,
        sidelen = 80,
        fill_ratio = 0.000500,
        y_max = sna.highland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:zufani",
        param2 = 2,
    },

    {--[[woodland:Vansano]]
        name = "wl_nn:vansano",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.001500,
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:vansano",
        param2 = 2,
    },

    {--[[woodland:Momo]]
        name = "wl_nn:momo_fruiting",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.001000,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:momo_fruiting",
        param2 = 2,
    },

    {--[[woodland:Rzepicha]]
        name = "wl_nn:rzepicha_fruiting",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.000100,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:rzepicha_fruiting",
        param2 = 0,
    },

    {--[[woodland:Malina]]
        name = "wl_nn:malina_fruiting",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.000100,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:malina_fruiting",
        param2 = 3,
    },

    {--[[woodland:Yellow Malina]]
        name = "wl_nn:yellow_malina_fruiting",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.000400,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:yellow_malina_fruiting",
        param2 = 3,
    },

    {--[[woodland:Zufani]]
        name = "wl_nn:zufani",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.000500,
        y_max = sna.highland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:zufani",
        param2 = 2,
    },

    {--[Grass&Shrub:Rzepicha]]
        name = "gs_nn:rzepicha_fruiting",
        deco_type = "simple",
        place_on = sna.grass_shrub_on,
        sidelen = 80,
        fill_ratio = 0.000020,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:rzepicha_fruiting",
        param2 = 0,
    },

    {--[[Grass&Shrub:Ttikusati]]
        name = "gs_nn:tikusati",
        deco_type = "simple",
        place_on = sna.grass_shrub_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0010, spread={x=100, y=100, z=100}, seed=1002, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.lowland_max,
        decoration = "nodes_nature:tikusati",
        param2 = 2,
    },

    {--[[Grass&Shrub:Wiha]]
        name = "nodes_nature:wiha_fruiting",
        deco_type = "simple",
        place_on = sna.grass_shrub_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0020, spread={x=32, y=32, z=32}, seed=1003, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:wiha_fruiting",
        param2 = 4,
    },

    {--[[Grass&Shrub:zufani]]
        name = "gs_nn:zufani",
        deco_type = "simple",
        place_on = sna.grass_shrub_on,
        sidelen = 80,
        fill_ratio = 0.001000,
        y_max = sna.highland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:zufani",
        param2 = 2,
    },

    {--[[grass_shrub_on:Tsaplop]]
        name = "gl_nn:tsaplop",
        deco_type = "simple",
        place_on = sna.grass_shrub_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0001, spread={x=32, y=32, z=32}, seed=5510, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.lowland_max,
        decoration = "nodes_nature:tsaplop",
        param2 = 0,
    },

    {--[[Duneland:anperla]]
        name = "dl_nn:anperla",
        deco_type = "simple",
        place_on = sna.duneland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0010, spread={x=32, y=32, z=32}, seed=1112, octaves=2, persist=0.8},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:anperla",
        param2 = 3,
    },

    {--[[Duneland:barszcz]]
        name = "dl_nn:barszcz",
        deco_type = "simple",
        place_on = sna.duneland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0010, spread={x=32, y=32, z=32}, seed=93, octaves=2, persist=0.8},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:barszcz",
        param2 = 2,
    },

    {--[[Duneland:Obesa]]
        name = "dl_nn:obesa_fruitless",
        deco_type = "simple",
        place_on = sna.duneland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0010, spread={x=32, y=32, z=32}, seed=950, octaves=2, persist=0.8},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:obesa_fruitless",
        param2 = 2,
    },

    {--[[Duneland:Tsaplop]]
        name = "dl_nn:tsaplop",
        deco_type = "simple",
        place_on = sna.duneland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0020, spread={x=32, y=32, z=32}, seed=5510, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:tsaplop",
        param2 = 0,
    },

    {--[[Duneland:muhle]]
        name = "dl_nn:muhle",
        deco_type = "simple",
        place_on = sna.duneland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.3000, spread={x=16, y=16, z=16}, seed=8500, octaves=3, persist=0.9},
        y_max = sna.highland_max,
        y_min = sna.lowland_max+5,
        decoration = "nodes_nature:muhle",
        param2 = 4,
    },

    {--[[Allbarren:muhle]]
        name = "bl_nn:muhle",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0300, spread={x=16, y=16, z=16}, seed=8500, octaves=3, persist=0.9},
        y_max = sna.highland_max,
        y_min = sna.lowland_max+5,
        decoration = "nodes_nature:muhle",
        param2 = 4,
    },

    {--[[highland:muhle]]
        name = "hl_nn:muhle",
        deco_type = "simple",
        place_on = sna.highland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0100, spread={x=16, y=16, z=16}, seed=8500, octaves=3, persist=0.9},
        y_max = 31000,
        y_min = sna.upland_max,
        decoration = "nodes_nature:muhle",
        param2 = 4,
    },

    {--[Allbarren:Rzepicha]]
        name = "bl_nn:rzepicha_fruiting",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 80,
        fill_ratio = 0.000002,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:rzepicha_fruiting",
        param2 = 0,
    },

    {--[[Allbarren:Tsaplop]]
        name = "bl_nn:tsaplop",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0002, spread={x=32, y=32, z=32}, seed=5510, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:tsaplop",
        param2 = 0,
    },

    {--[[Allbarren:Obesa]]
        name = "bl_nn:obesa_fruitless",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0002, spread={x=32, y=32, z=32}, seed=950, octaves=2, persist=0.8},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:obesa_fruitless",
        param2 = 2,
    },

    {--[[Allbarren:Ttikusati]]
        name = "bl_nn:tikusati",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0005, spread={x=100, y=100, z=100}, seed=1002, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.lowland_max,
        decoration = "nodes_nature:tikusati",
        param2 = 2,
    },

    {--[[Allbarren:anperla]]
        name = "bl_nn:anperla",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0001, spread={x=32, y=32, z=32}, seed=1112, octaves=2, persist=0.8},
        y_max = sna.coastal_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:anperla",
        param2 = 3,
    },

    {--[[barrenland:zufani]]
        name = "bl_nn:zufani",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 80,
        fill_ratio = 0.000010,
        y_max = sna.highland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:zufani",
        param2 = 2,
    },

    {--[[Allbarren:Wiha]]
        name = "bl_nn:wiha_fruiting",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0001, spread={x=32, y=32, z=32}, seed=1003, octaves=2, persist=0.9},
        y_max = sna.lowland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:wiha_fruiting",
        param2 = 4,
    },

    {--[[Allbarren:barszcz]]
        name = "bl_nn:barszcz",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0004, spread={x=32, y=32, z=32}, seed=93, octaves=2, persist=0.9},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:barszcz",
        param2 = 2,
    },

    -- End of edible
}

local kind_of_edible_plants = {
    {--[[richforest:merki]]
        name = "rf_nn:merki",
        deco_type = "simple",
        place_on = sna.rich_forest_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0200, spread={x=32, y=32, z=32}, seed=1112, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.lowland_max,
        decoration = "nodes_nature:merki",
        param2 = 2,
    },

    {--[[forest:merki]]
        name = "fr_nn:merki",
        deco_type = "simple",
        place_on = sna.forest_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0200, spread={x=32, y=32, z=32}, seed=1112, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.lowland_max,
        decoration = "nodes_nature:merki",
        param2 = 2,
    },

    {--[[woodland:ziarnoplon]]
        name = "wl_nn:ziarnoplon",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.030000,
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:ziarnoplon",
        param2 = 3,
    },

    {--[[woodland:srebroplon]]
        name = "wl_nn:srebroplon",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.000090,
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:srebroplon",
        param2 = 3,
    },

    {--[[woodland:hakimi]]
        name = "wl_nn:hakimi",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.001000,
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:hakimi",
        param2 = 3,
    },

    {--[[Grass&Shrub:hakimi]]
        name = "gs_nn:hakimi",
        deco_type = "simple",
        place_on = sna.grass_shrub_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0010, spread={x=100, y=100, z=100}, seed=1004, octaves=2, persist=0.8},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:hakimi",
        param2 = 3,
    },

    {--[[Allbarren:hakimi]]
        name = "bl_nn:hakimi",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0001, spread={x=100, y=100, z=100}, seed=1004, octaves=2, persist=0.85},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:hakimi",
        param2 = 3,
    },

    -- End of kind_of_edible
}

local toxic_plants = {
    {--[[wetland:marbhan]]
        name = "nodes_nature:marbhan",
        deco_type = "simple",
        place_on = sna.wetland_on,
        sidelen = 80,
        fill_ratio = 0.001500,
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:marbhan",
        param2 = 2,
    },

    {--[[woodland:nebiyi]]
        name = "wl_nn:nebiyi",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 80,
        fill_ratio = 0.001000,
        y_max = sna.highland_max,
        y_min = sna.lowland_max,
        decoration = "nodes_nature:nebiyi",
        param2 = 1,
    },

    {--[[Grassland:wrotycz]]
        name = "gl_nn:wrotycz_flowering",
        deco_type = "simple",
        place_on = sna.grassland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0020, spread={x=32, y=32, z=32}, seed=1003, octaves=2, persist=0.7},
        y_max = sna.highland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:wrotycz_flowering",
        param2 = 1,
    },

    {--[[Grassland:barszcz]]
        name = "gl_nn:barszcz",
        deco_type = "simple",
        place_on = sna.grassland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0010, spread={x=32, y=32, z=32}, seed=93, octaves=2, persist=0.8},
        y_max = sna.lowland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:barszcz",
        param2 = 3,
    },

    {--[[Grassland:salia]]
        name = "gl_nn:salia",
        deco_type = "simple",
        place_on = sna.grassland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0030, spread={x=16, y=16, z=16}, seed=9900, octaves=3, persist=0.9},
        y_max = sna.lowland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:salia",
        param2 = 4,
    },

    {--[[Shrubland:salia]]
        name = "sh_nn:salia",
        deco_type = "simple",
        place_on = sna.shrubland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0020, spread={x=16, y=16, z=16}, seed=9900, octaves=3, persist=0.9},
        y_max = sna.lowland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:salia",
        param2 = 4,
    },

    {--[[Shrubland:fretin]]
        name = "sh_nn:fretin",
        deco_type = "simple",
        place_on = sna.shrubland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.3000, spread={x=16, y=16, z=16}, seed=1188, octaves=3, persist=0.7},
        y_max = sna.upland_max,
        y_min = sna.lowland_max-5,
        decoration = "nodes_nature:fretin",
        param2 = 2,
    },

    {--[[Woodland:fretin]]
        name = "wl_nn:fretin",
        deco_type = "simple",
        place_on = sna.woodland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.1000, spread={x=16, y=16, z=16}, seed=1188, octaves=3, persist=0.7},
        y_max = sna.upland_max,
        y_min = sna.lowland_max-5,
        decoration = "nodes_nature:fretin",
        param2 = 2,
    },

    {--[[forest:fretin]]
        name = "fr_nn:fretin",
        deco_type = "simple",
        place_on = sna.forest_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0500, spread={x=16, y=16, z=16}, seed=1188, octaves=3, persist=0.7},
        y_max = sna.upland_max,
        y_min = sna.lowland_max-5,
        decoration = "nodes_nature:fretin",
        param2 = 2,
    },

    {--[[Grassland:fretin]]
        name = "gl_nn:fretin",
        deco_type = "simple",
        place_on = sna.grassland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0500, spread={x=16, y=16, z=16}, seed=1188, octaves=3, persist=0.7},
        y_max = sna.upland_max,
        y_min = sna.lowland_max-5,
        decoration = "nodes_nature:fretin",
        param2 = 2,
    },

    {--[[shrubland:nebiyi]]
        name = "sh_nn:nebiyi",
        deco_type = "simple",
        place_on = sna.shrubland_on,
        sidelen = 80,
        fill_ratio = 0.001000,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:nebiyi",
        param2 = 1,
    },

    {--[[Allbarren:nebiyi]]
        name = "bl_nn:nebiyi",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 80,
        fill_ratio = 0.001000,
        y_max = sna.highland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:nebiyi",
        param2 = 1,
    },

    {--[[Allbarren:salia]]
        name = "bl_nn:salia",
        deco_type = "simple",
        place_on = sna.barrenland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.3000, spread={x=16, y=16, z=16}, seed=9900, octaves=3, persist=0.8},
        y_max = sna.lowland_max,
        y_min = sna.coastal_max,
        decoration = "nodes_nature:salia",
        param2 = 4,
    },


    {--[[Duneland:Gevaari]]
        name = "dl_nn:gevaari",
        deco_type = "simple",
        place_on = sna.duneland_on,
        sidelen = 16,
        noise_params = {offset=0.00, scale=0.0010, spread={x=32, y=32, z=32}, seed=983, octaves=2, persist=0.8},
        y_max = sna.highland_max,
        y_min = sna.beach_max,
        decoration = "nodes_nature:gevaari",
        param2 = 1,
    },
    -- End of toxic
}

return {
    edible_plants = edible_plants,
    kind_of_edible_plants = kind_of_edible_plants,
    toxic_plants = toxic_plants,
}
