
--food_data.lua
--Contains data for all the predefined foods in Exile.
--[[Some notes:
	Calculating sensible values for food:
	(intervals/day) * hunger_rate = daily basal food needs
	i.e. 20 min/1 min * 2 = 40 units per day

	Therefore 40 units = 2,000 Calories.
	 calories -> units = 2,000/40 = 50 kcal/unit

	Sugar   3,900 kcal/kg = 78.0 units/kg  172.0 per lb.
	Bread   2,600 kcal/kg = 52.0 units/kg  115.0 per lb.
	Potato    750 kcal/kg = 15.0 units/kg   33.0 per lb.
	Meat    2,000 kcal/kg = 40.0 units/kg   88.0 per lb.
	cabbage   240 kcal/kg =  4.8 units/kg   10.5 per lb.
	]]--

food_table = {
	--name	     	      	               hp  th  hu   en  temp, replacewithitem (not implemented yet)
	["tech:maraka_bread_cooked"]        = {hu=24,en=14},
	["tech:maraka_bread_burned"]        = {hu=12,en=7},
	["tech:peeled_anperla_cooked"]      = {th=2,hu=12,en=7},
    ["nodes_nature:rzepicha_root"]      = {th=4,hu=35,en=5},
    ["nodes_nature:rzepicha_root_winter"]      = {th=4,hu=35,en=5},
	--example: burned anperla tubers are inedible, so no entry
	["tech:mashed_anperla_cooked"]      = {th=12,hu=72,en=42},
	["tech:mashed_anperla_burned"]      = {th=6,hu=36,en=21},
	["nodes_nature:sea_lettuce"]        = {hu=5,en=-10},
	["nodes_nature:sea_lettuce_cooked"] = {hu=5},
	["nodes_nature:vansano_seed"]       = {hu=1},
	["nodes_nature:tikusati_seed"]      = {hu=-2,en=2},
	--food and water                       hp  th   hu  en  te
        ["nodes_nature:wiha_fruitless"]     = {th=3,hu=1},
        ["nodes_nature:wiha_flowering"]     = {th=4,hu=2},
        ["nodes_nature:wiha_fruiting"]      = {th=8,hu=4},
        ["nodes_nature:wiha_fruit"]         = {th=4,hu=2},
        ["nodes_nature:jalowiec_cone"]      = {th=1,hu=1},
        ["nodes_nature:ziarnoplon_fruitless"]     = {th=3,hu=1},
        ["nodes_nature:ziarnoplon_flowering"]     = {th=2,hu=1,en=-6},
        ["nodes_nature:ziarnoplon_fruiting"]      = {th=3,hu=4,en=-4},
        ["nodes_nature:ziarnoplon_fruit"]         = {th=1,hu=1,en=-4},
        ["nodes_nature:srebroplon_fruitless"]     = {th=3,hu=1},
        ["nodes_nature:srebroplon_flowering"]     = {th=2,hu=1,en=-6},
        ["nodes_nature:srebroplon_fruiting"]      = {th=3,hu=4,en=-4},
        ["nodes_nature:srebroplon_fruit"]         = {th=1,hu=1,en=-4},
        ["nodes_nature:obesa_fruit"]        = {th=8,hu=1},
        ["nodes_nature:malina_fruit"]       = {th=2,hu=4},
        ["nodes_nature:yellow_malina_fruit"]= {th=3,hu=4},
        ["nodes_nature:malinka_fruit"]      = {th=2,hu=2},
	    ["nodes_nature:zufani"]             = {hu=6},
        ["nodes_nature:zufani_fruit"]       = {hu=4,en=4},
        ["nodes_nature:damo_seedling1"]     = {th=1,hu=1},
        ["nodes_nature:damo_seedling2"]     = {th=1,hu=1},
        ["nodes_nature:damo_seedling3"]     = {th=1,hu=1},
        ["nodes_nature:damo_seedling4"]     = {th=1,hu=2},
        ["nodes_nature:damo_seedling5"]     = {th=1,hu=2},
        ["nodes_nature:galanta_seedling1"]  = {th=1,hu=1},
        ["nodes_nature:galanta_seedling2"]  = {th=1,hu=1},
        ["nodes_nature:galanta_seedling3"]  = {th=1,hu=1},
        ["nodes_nature:galanta_seedling4"]  = {th=1,hu=2},
        ["nodes_nature:galanta_seedling5"]  = {th=1,hu=2},
        ["nodes_nature:galanta"]            = {th=1,hu=3},
	    ["nodes_nature:lambakap"]           = {th=10,hu=10},
	    ["nodes_nature:tangkal_fruit"]      = {th=5,hu=10,en=10},
	    ["nodes_nature:panasee_fruit"]      = {th=5,hu=4,en=1},
	    ["nodes_nature:amma_nut"]           = {hu=1,en=10},
	    ["nodes_nature:daoja_berry"]        = {hu=4},
        ["nodes_nature:momo_fruit"]         = {th=1,hu=12},
        ["nodes_nature:momo_fruiting"]      = {th=1,hu=15},
        ["nodes_nature:momo_fruitless"]     = {th=1,hu=3},
        ["nodes_nature:barszcz_fruit"]      = {th=1,hu=1},
        ["nodes_nature:barszcz_fruiting"]   = {th=1,hu=3},
        ["nodes_nature:barszcz_flowering"]  = {th=1,hu=2},
        ["nodes_nature:barszcz_fruitless"]  = {th=1,hu=2},
        ["nodes_nature:barszcz_root"]       = {th=1,hu=4,en=1},
	    ["nodes_nature:tsaplop"]            = {th=10,hu=10},
	    ["nodes_nature:snow"]               = {th=50,en=-100,temp=-1},
	    ["nodes_nature:snow_block"]         = {th=100,en=-200,temp=-2},
	--meat
     ["animals:carcass_invert_small"]       = {hu=3, en=-2},
     ["animals:carcass_invert_small_cooked"]= {hu=6,en=1},
     ["animals:carcass_invert_small_burned"]= {th=-1,hu=1,en=-3},
     ["animals:carcass_invert_large"]       = {th=1,hu=10,en=-6},
     ["animals:carcass_invert_large_cooked"]= {th=1,hu=20,en=3},
     ["animals:carcass_invert_large_burned"]= {th=-1,hu=2,en=-7},
     ["animals:carcass_bird_small"]         = {th=1,hu=20,en=-4},
     ["animals:carcass_bird_small_cooked"]  = {th=1,hu=40,en=2},
     ["animals:carcass_bird_small_burned"]  = {th=-1,hu=5,en=-5},
     ["animals:carcass_fish_small"]         = {th=1,hu=15,en=-4},
     ["animals:carcass_fish_small_cooked"]  = {th=2,hu=30,en=2},
     ["animals:carcass_fish_small_burned"]  = {th=-1,hu=5,en=-5},
     ["animals:carcass_fish_large"]         = {th=3,hu=45,en=-12},
     ["animals:carcass_fish_large_cooked"]  = {th=3,hu=90,en=6},
     ["animals:carcass_fish_large_burned"]  = {th=-1,hu=21,en=-13},
	--eggs
	["animals:darkasthaan_eggs"]        = {th=1,hu=10},
	["animals:gundu_eggs"]              = {th=10,hu=30},
	["animals:impethu_eggs"]            = {hu=4},
	["animals:kubwakubwa_eggs"]         = {hu=6},
	["animals:pegasun_eggs"]            = {hu=5},
	["animals:sarkamos_eggs"]           = {th=10,hu=40},
	["animals:sneachan_eggs"]           = {hu=3},
	--drugs
	["nodes_nature:tikusati"]           = {hu=-2,en=2},
	--toxic
        ["nodes_nature:momo_flowering"]     = {th=1,hu=3},
        ["nodes_nature:wrotycz_fruit"]      = {hu=2},
	["nodes_nature:nebiyi"]             = {hu=1,en=-10},
	["nodes_nature:marbhan"]            = {hu=1,en=-10},
        ["nodes_nature:gevaari"]            = {hp=-2,hu=1,en=-10},
        ["nodes_nature:obesa_fruitless"]    = {hp=-2,th=10,hu=6,en=-4},
        ["nodes_nature:obesa_fruiting"]     = {hp=-2,th=10,hu=6,en=-4},
        ["nodes_nature:obesa_flowering"]    = {hp=-2,th=10,hu=6,en=-4},
	["nodes_nature:maraka_nut"]         = {hu=5,en=5},
	["nodes_nature:sasaran_cone"]       = {hu=1},
	--medicine                              hp  th   hu  en  te
	["nodes_nature:hakimi_flowering"]             = {hp=1,hu=1,en=-15},
	["nodes_nature:merki"]              = {hp=1,hu=1,en=-15},
	}

bake_table = {
	--name                          temp, duration, optional food value?
   ["tech:maraka_bread"]              = { 160,  10 },
   ["tech:peeled_anperla"]            = { 100,   7 },
   ["tech:mashed_anperla"]            = { 100,  35 },
   ["nodes_nature:sea_lettuce"]       = { 100,   3 },
   ["animals:carcass_invert_small"]   = { 100,   1 },
   ["animals:carcass_invert_large"]   = { 100,   3 },
   ["animals:carcass_bird_small"]     = { 100,   6 },
   ["animals:carcass_fish_small"]     = { 100,   6 },
   ["animals:carcass_fish_large"]     = { 100,  18 },
}

food_harm_table = {
	--name                     { {tag, chance, severity}, {t, c, s}, etc }
	["tech:maraka_bread_cooked"]     = { { "Food Poisoning",      0.001, 1} },
	["tech:maraka_bread_burned"]     = { { "Food Poisoning",      0.001, 1} },
	["tech:peeled_anperla_cooked"]   = { { "Food Poisoning",      0.002, 1} },

	["tech:mashed_anperla_cooked"]   = { { "Food Poisoning",      0.002, 1} },
	["tech:mashed_anperla_burned"]   = { { "Food Poisoning",      0.002, 1} },
	["nodes_nature:sea_lettuce"]     = { { "Food Poisoning",      0.050, 1},
	                                     {"Intestinal Parasites", 0.010   } },
	["nodes_nature:sea_lettuce_cooked"] = { { "Food Poisoning",   0.002, 1} },
	["nodes_nature:vansano_seed"]    = { { "Food Poisoning",      0.001, 1} },
	["nodes_nature:tikusati_seed"]   = { { "Food Poisoning",      0.001, 1} },
	["nodes_nature:tikusati"]        = { { "Food Poisoning",      0.001, 1} },
	["nodes_nature:nebiyi"]          = { { "Food Poisoning",      0.001, 1} },
	["nodes_nature:marbhan"]         = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:gevaari"]         = { { "Food Poisoning",      0.001, 1},
            { "Hepatotoxicity",      1.0, 1}},
        ["nodes_nature:obesa"]         = { { "Food Poisoning",      0.5, 1},
            { "Hepatotoxicity",      0.001, 1}},
        ["nodes_nature:obesa_flowering"]         = { { "Food Poisoning",      0.5, 1},
            { "Hepatotoxicity",      0.001, 1}},
        ["nodes_nature:obesa_fruitless"]         = { { "Food Poisoning",      0.5, 1},
            { "Hepatotoxicity",      0.001, 1}},
        ["nodes_nature:obesa_fruit"]       = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:ziarnoplon_flowering"]         = { { "Food Poisoning",      0.6, 1},
            { "Hepatotoxicity",      0.1, 1}},
        ["nodes_nature:ziarnoplon_fruit"]             = { { "Food Poisoning",      0.6, 1},
            { "Hepatotoxicity",      0.1, 1}},
        ["nodes_nature:ziarnoplon_fruiting"]             = { { "Food Poisoning",      0.6, 1},
            { "Hepatotoxicity",      0.1, 1}},
        ["nodes_nature:ziarnoplon_fruitless"]         = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:srebroplon_flowering"]         = { { "Food Poisoning",      0.6, 1},
            { "Hepatotoxicity",      0.1, 1}},
        ["nodes_nature:srebroplon_fruit"]             = { { "Food Poisoning",      0.6, 1},
            { "Hepatotoxicity",      0.1, 1}},
        ["nodes_nature:srebroplon_fruiting"]             = { { "Food Poisoning",      0.6, 1},
            { "Hepatotoxicity",      0.1, 1}},
        ["nodes_nature:srebroplon_fruitless"]         = { { "Food Poisoning",      0.001, 1} },
	["nodes_nature:hakimi"]          = { { "Food Poisoning",      0.001, 1} },
	["nodes_nature:merki"]           = { { "Food Poisoning",      0.001, 1} },
	["nodes_nature:zufani"]          = { { "Food Poisoning",      0.010, 1} },
        ["nodes_nature:galanta"]         = { { "Food Poisoning",      0.008, 1} },
        ["nodes_nature:galanta_seedling1"]  = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:galanta_seedling2"]  = { { "Food Poisoning",      0.002, 1} },
        ["nodes_nature:galanta_seedling3"]  = { { "Food Poisoning",      0.003, 1} },
        ["nodes_nature:galanta_seedling4"]  = { { "Food Poisoning",      0.004, 1} },
        ["nodes_nature:galanta_seedling5"]  = { { "Food Poisoning",      0.005, 1} },
        ["nodes_nature:damo_seedling1"]  = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:damo_seedling2"]  = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:damo_seedling3"]  = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:damo_seedling4"]  = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:damo_seedling5"]  = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:momo_fruiting"]   = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:momo_fruitless"]  = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:momo_flowering"]  = { { "Food Poisoning",      0.400, 1},
            { "Hepatotoxicity", 0.3, math.floor(math.random(1,2)) }},
        ["nodes_nature:barszcz_fruiting"]   = { { "Food Poisoning",      0.400, 1},
            { "Hepatotoxicity", 0.1, math.floor(math.random(1,2)) }},
        ["nodes_nature:barszcz_fruitless"]  = { { "Food Poisoning",      0.400, 1},
            { "Hepatotoxicity", 0.1, math.floor(math.random(1,2)) }},
        ["nodes_nature:barszcz_flowering"]  = { { "Food Poisoning",      0.400, 1},
            { "Hepatotoxicity", 0.1, math.floor(math.random(1,2)) }},
        ["nodes_nature:barszcz_root"]       = { { "Food Poisoning",      0.01, 1},
            { "Hepatotoxicity", 0.01, math.floor(math.random(1,2)) }},
        ["nodes_nature:rzepicha_root"]     = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:rzepicha_root_winter"]     = { { "Food Poisoning",      0.001, 1} },

        --fruit
        ["nodes_nature:wrotycz_fruit"]   = { { "Food Poisoning",      0.100, 1},
            { "Hepatotoxicity",      0.005, 1} },
        ["nodes_nature:momo_fruit"]      = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:barszcz_fruit"]      = { { "Food Poisoning",      0.400, 1},
            { "Hepatotoxicity", 0.1, math.floor(math.random(1,2)) }},
        ["nodes_nature:malina_fruit"]      = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:yellow_malina_fruit"]      = { { "Food Poisoning",      0.001, 1} },
        ["nodes_nature:malinka_fruit"]      = { { "Food Poisoning",      0.001, 1} },

	--Trees fruit
	["nodes_nature:maraka_nut"]      = { { "Food Poisoning",      0.001, 1},
	                                     { "Hepatotoxicity",      0.005, math.floor(math.random(1,4)) },
	                                     { "Photosensitivity",    0.300, 1} },
  ["nodes_nature:sasaran_cone"]    = { { "Food Poisoning",      0.08, 1} },
	["nodes_nature:tangkal_fruit"]   = { { "Food Poisoning",      0.001, 1},
	                                     { "Drunk",               0.005, 1} },
  ["nodes_nature:panasee_fruit"]   = { { "Food Poisoning",      0.001, 1} },
	--To do: add mild stimulant for Amma (like coffee)?
	["nodes_nature:amma_nut"]        = { { "Food Poisoning",      0.001, 1} },
	["nodes_nature:daoja_berry"]     = { { "Food Poisoning",      0.001, 1},
																			 { "Hepatotoxicity",      0.200, 1}},

	--meat
	["animals:carcass_invert_small"] = { { "Food Poisoning",      0.1,   1},
	                                     { "Intestinal Parasites",0.01,  1} },
	["animals:carcass_invert_small_cooked"] = { { "Food Poisoning", 0.002, 1} },
	["animals:carcass_invert_small_burned"] = { { "Food Poisoning", 0.001, 1} },
	["animals:carcass_invert_large"] = { { "Food Poisoning",      0.2,   1},
	                                     { "Intestinal Parasites",0.02,  1} },
	["animals:carcass_invert_large_cooked"] = { { "Food Poisoning",0.002,   1} },
	["animals:carcass_invert_large_burned"] = { { "Food Poisoning",0.001,   1} },
	["animals:carcass_bird_small"]   = { { "Food Poisoning",      0.05,  1},
	                                     { "Intestinal Parasites",0.02,  1} },
	["animals:carcass_bird_small_cooked"] = { { "Food Poisoning", 0.002,  1} },
	["animals:carcass_bird_small_burned"] = { { "Food Poisoning", 0.001,  1} },
	["animals:carcass_fish_small"]   = { { "Food Poisoning",      0.05,  1},
	                                     { "Intestinal Parasites",0.02,  1} },
	["animals:carcass_fish_small_cooked"] = { { "Food Poisoning", 0.002,  1} },
	["animals:carcass_fish_small_burned"] = { { "Food Poisoning", 0.001,  1} },
	["animals:carcass_fish_large"]   = { { "Food Poisoning",      0.1,   1},
	                                     { "Intestinal Parasites",0.04,  1} },
	["animals:carcass_fish_large_cooked"] = { { "Food Poisoning", 0.004, 1} },
	["animals:carcass_fish_large_burned"] = { { "Food Poisoning", 0.002, 1} },
	--eggs
	["animals:darkasthaan_eggs"]     = { { "Food Poisoning",      0.1,
					       math.floor(math.random(1,4))},
	                                     { "Intestinal Parasites",0.01, 1} },
	["animals:gundu_eggs"]           = { { "Food Poisoning",      0.05,
					       math.floor(math.random(1,4))},
	                                     { "Intestinal Parasites",0.1,  1} },
	["animals:impethu_eggs"]         = { { "Food Poisoning",      0.1,
					       math.floor(math.random(1,4))},
	                                     { "Intestinal Parasites",0.1,  1} },
	["animals:kubwakubwa_eggs"]      = { { "Food Poisoning",      0.1,
					       math.floor(math.random(1,4))},
	                                     { "Intestinal Parasites",0.01, 1} },
	["animals:pegasun_eggs"]         = { { "Food Poisoning",      0.02,
					       math.floor(math.random(1,2))},
	                                     { "Intestinal Parasites",0.005, 1} },
	["animals:sarkamos_eggs"]       = { { "Food Poisoning",      0.3,
					       math.floor(math.random(1,4))},
	                                     { "Intestinal Parasites",0.05, 1} },
	["animals:sneachan_eggs"]       = { { "Food Poisoning",      0.5,
					       math.floor(math.random(1,4))},
	                                     { "Intestinal Parasites",0.5, 1} },
	}
