---------------------------------------------------------
--Plant seasonal types

-- Internationalization
local S = nodes_nature.S

---------------------------------------------------------

seasonal_types = {
    early = {
        _spring_early = "_seedling3",
        _spring_late = "_flowering",
        _summer_early = "_fruiting",
        _summer_late = "_fruiting",
        _fall_early = "_fruiting",
        _fall_late = "_dead",
        _winter_early = "_dead",
        _winter_late = "_seed",
    },
    medium = {
        _spring_early = "_seed",
        _spring_late = "_seedling3",
        _summer_early = "_flowering",
        _summer_late = "_fruiting",
        _fall_early = "_fruiting",
        _fall_late = "_dead",
        _winter_early = "_dead",
        _winter_late = "_dead",
    },
    long = {
        _spring_early = "_seedling5",
        _spring_late = "_fruitless",
        _summer_early = "_flowering",
        _summer_late = "_fruiting",
        _fall_early = "_fruiting",
        _fall_late = "_fruiting",
        _winter_early = "_dead",
        _winter_late = "_dead",
    },
    late = {
        _spring_early = "_dead",
        _spring_late = "_seedling3",
        _summer_early = "_seedling5",
        _summer_late = "_flowering",
        _fall_early = "_fruiting",
        _fall_late = "_fruiting",
        _winter_early = "_dead",
        _winter_late = "_dead",
    },
    late_mushroom = {
        _spring_early = "_dead",
        _spring_late = "_seed",
        _summer_early = "_seed",
        _summer_late = "_seedling5",
        _fall_early = "",
        _fall_late = "",
        _winter_early = "_dead",
        _winter_late = "_dead",
    },
    mainly_flower = {
        _spring_early = "_seedling3",
        _spring_late = "_flowering",
        _summer_early = "_flowering",
        _summer_late = "_flowering",
        _fall_early = "_fruiting",
        _fall_late = "_dead",
        _winter_early = "_dead",
        _winter_late = "_seed",
    },
    whole_season = {
        _spring_early = "_seedling5",
        _spring_late = "",
        _summer_early = "",
        _summer_late = "",
        _fall_early = "",
        _fall_late = "",
        _winter_early = "_dead",
        _winter_late = "_dead",
    },
    cane = {
        _spring_early = "",
        _spring_late = "",
        _summer_early = "",
        _summer_late = "",
        _fall_early = "",
        _fall_late = "",
        _winter_early = "_dead",
        _winter_late = "_dead",
    },
    whole_season_woody = {
        _spring_early = "",
        _spring_late = "",
        _summer_early = "",
        _summer_late = "",
        _fall_early = "",
        _fall_late = "",
        _winter_early = "_dead",
        _winter_late = "_dead",
    },
    tuber = {
        _spring_early = "_seedling5",
        _spring_late = "_flowering",
        _summer_early = "_fruiting",
        _summer_late = "_fruiting",
        _fall_early = "_fruitless",
        _fall_late = "_dead",
        _winter_early = "_dead",
        _winter_late = "_dead",
    },
}
