when:
  - event: push
    branch: action_test

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0

steps:
  - name: luacheck
    image: pipelinecomponents/luacheck
    commands:
      - echo "This is a test"
