clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      depth: 0

when:
  - event: push
    branch: action_test

steps:
  - name: luacheck
    image: pipelinecomponents/luacheck
    commands:
      - echo "This is a test"
